language: python
sudo: required
dist: bionic
python:
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
install:
  - pip install -r dev_requirements.txt
script: pytest --cov=./app
after_success:
  - codecov
